# Generated by Django 3.2.13 on 2022-09-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commpleted',
            new_name='completed',
        ),
    ]
